// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_unlock_the_dawn_level = "CgkIlY-bvcoNEAIQBg"; // <GPGSID>
        public const string achievement_unlock_the_rainy_level = "CgkIlY-bvcoNEAIQEA"; // <GPGSID>
        public const string achievement_unlock_the_winter_level = "CgkIlY-bvcoNEAIQDQ"; // <GPGSID>
        public const string achievement_unlock_the_green_bird = "CgkIlY-bvcoNEAIQBQ"; // <GPGSID>
        public const string achievement_pass_the_score_30 = "CgkIlY-bvcoNEAIQAw"; // <GPGSID>
        public const string achievement_became_the_ultimate_flappy = "CgkIlY-bvcoNEAIQEQ"; // <GPGSID>
        public const string achievement_unlock_the_evening_level = "CgkIlY-bvcoNEAIQDg"; // <GPGSID>
        public const string achievement_unlock_farm_level = "CgkIlY-bvcoNEAIQDA"; // <GPGSID>
        public const string achievement_unlock_the_red_bird = "CgkIlY-bvcoNEAIQCA"; // <GPGSID>
        public const string achievement_unlock_the_spring_level = "CgkIlY-bvcoNEAIQCw"; // <GPGSID>
        public const string achievement_become_a_centurian = "CgkIlY-bvcoNEAIQBw"; // <GPGSID>
        public const string achievement_unlock_the_mountains_level = "CgkIlY-bvcoNEAIQCQ"; // <GPGSID>
        public const string leaderboard_flappy_the_bird_leaderboard = "CgkIlY-bvcoNEAIQAQ"; // <GPGSID>
        public const string achievement_unlock_the_lake_level = "CgkIlY-bvcoNEAIQCg"; // <GPGSID>
        public const string achievement_score_5 = "CgkIlY-bvcoNEAIQAg"; // <GPGSID>
        public const string achievement_unlock_the_dark_level = "CgkIlY-bvcoNEAIQDw"; // <GPGSID>

}

